'use client'

import { useState } from 'react';
import Head from "next/head";
import { FaUser } from "react-icons/fa";
import { MdChair, MdLocationPin } from "react-icons/md";
import { IoSwapHorizontal } from "react-icons/io5";
import PriceSlider from '@/components/common/PriceBar/PriceSlider';
import AvailableFlight from '@/components/AvailableFlight/AvailableFlight';
import DateTimePicker from '@/components/common/DatePicker/DatePicker';
import SideBar from '@/components/SideBar/SideBar';
import Dropdown from '@/components/common/DropDown/DropDown';
import { Way } from '@/types/types';
import styles from './page.module.css'

const Home = () => {
  const [activeWay, setActiveWay] = useState<string | null>(null);

  const wayOptionList: Way[] = [
    { id: "1", name: 'ONE WAY' },
    { id: "2", name: 'ROUND TRIP' },
    { id: "3", name: 'MULTI CITY' },
  ];

  const handleActiveWayOption = (id: string) => {
    setActiveWay(id);
  };

  const yourOptions = [
    { value: 'option1', label: 'Option 1' },
    { value: 'option2', label: 'Option 2' },
    { value: 'option3', label: 'Option 3' },
  ];

  const handleSelect = (option: any) => {
    console.log('You selected:', option.label);
  };

  const handlePrice = (min: number, max: number) => {
    console.log(min, max);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`container ${styles.home}`}>
        <div className={styles.sidebar}>
          <SideBar />
        </div>

        <div className={styles.main}>
          <section className={styles.travelOptions}>

            <div className={styles.travelOptionsRight}>

              <div className={styles.locationOption}>
                <span className={styles.locationFrom}>
                <MdLocationPin className={styles.loationIcon} />
                  NEW YORK (JFK)
                </span>
                <span className={styles.horizonIcon}>
                  <IoSwapHorizontal />
                </span>
                <span className={styles.locationTo}>
                  <MdLocationPin className={styles.loationIcon} />
                  MUMBAI (BOM)
                </span>
              </div>

              <div className={styles.wayOption}>
                {wayOptionList.map((way) => (
                  <span
                    key={way.id}
                    className={activeWay === way.id ? styles.active : ''}
                    onClick={() => handleActiveWayOption(way.id)}
                  >
                    {way.name}
                  </span>
                ))}
              </div>
            </div>

            <div className={styles.travelOptionsLeft}>
              <div className={styles.travelOptionsLeftDetail}>
                <span className={styles.dateWrapper}>
                  <DateTimePicker />
                </span>

                <span>
                  <FaUser />
                  2 TRAVELLERS
                </span>

              </div>

              <div className={styles.travelOptionsLeftDetail}>
                <span>
                  <MdChair />
                  FIRST CLASS
                </span>

                <span>
                  SEARCH
                </span>
              </div>
            </div>

          </section>

          <section className={styles.resultFilter}>
            <span className={styles.result}>
              RESULT(25)
            </span>

            <div className={styles.filter}>
              <span >
                FILTER
              </span>
              <span>
                <Dropdown label="TICKET OF CLASS" options={yourOptions} onSelect={handleSelect} />
              </span>

            </div>
          </section>

          <section className={styles.sectionC}>

            <div className={styles.availableFlights}>
              <AvailableFlight borderTopCurve={false} borderBottomCurve={true} borderLine={true} />
              <AvailableFlight borderTopCurve={true} borderBottomCurve={true} borderLine={true} />
              <AvailableFlight borderTopCurve={true} borderBottomCurve={true} borderLine={true} />
              <AvailableFlight borderTopCurve={true} borderBottomCurve={true} borderLine={true} />
              <AvailableFlight borderTopCurve={true} borderBottomCurve={true} borderLine={true} />
              <AvailableFlight borderTopCurve={true} borderBottomCurve={true} borderLine={true} />
              <AvailableFlight borderTopCurve={true} borderBottomCurve={false} borderLine={false} />
            </div>


            <div className={styles.destinationDetails}>
              <div className={styles.destinationDetailsDirection} >
                <span>
                  FROM
                  <p>
                    JFK
                  </p>
                </span>
                <span>
                  NON-STOP
                </span>
                <span>
                  TO
                  <p>
                    BOM
                  </p>
                </span>
              </div>

              <div className={styles.destinationMap}>

              </div>

              <div className={styles.destinationOptions2}>
                <span>NON STOP</span>
                <span>ONE STOP</span>
                <span>MORE STOP</span>
              </div>

              <PriceSlider
                min={0}
                max={1000}
                onChange={({ min, max }) => handlePrice(min, max)}
              />
            </div>

          </section>
        </div>
      </div>
    </>
  );
};

export default Home;
